version: '3.3'
services:
    debian-wifioverbt:
        restart: unless-stopped
        privileged: true
        network_mode: host
        volumes:
            - './service:/etc/systemd/system/dbus-org.bluez.service:ro'
            - './start.sh:/start.sh'
        image: 'gtntdev/debian-wifioverbt:1.0'
